### ISSUE TITLE
Issue when running highstate

### ISSUE THREAD

**Issue by TaiSHiNet** [saltstack-formulas/php-formula#16]
I tried my own pillar and the default pillar.example, minion is running latest dev.
Tried playing with the code a bit, but really have no idea where is it imploding.

```
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://php/ng/fpm/pools_config.sls'
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://php/ng/map.jinja'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://php/ng/macro.jinja'
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/php/ng/fpm/pools_config.sls:
# Manages the php-fpm pools config files

# Simple path concatenation.

[DEBUG   ] Results of YAML rendering: 
{}
Passed invalid arguments: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 91, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 287, in highstate
    whitelist=kwargs.get('whitelist')
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2768, in call_highstate
    return self.state.call_high(high)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1886, in call_high
    high, ext_errors = self.reconcile_extend(high)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1156, in reconcile_extend
    .extend(arg[argfirst]))
TypeError: 'NoneType' object is not iterable
```

**Comment by rskuipers** [comment]
@TaiSHiNet Do you remember what was wrong? I'm getting this same error on `php.ng.fpm`.

**Comment by rskuipers** [comment]
@TaiSHiNet Never mind, I forgot to define my pillars in pillars/top.sls >.<

**Comment by alrayyes** [comment]
I'm getting the same error. My pillar looks like this:

```yaml
php:
  ng:
    version: 7.0
```

Running in Debian Jessie. Is there something I'm missing?

**Comment by alrayyes** [comment]
Never mind, Found the solution in #47, specifically [this comment](https://github.com/saltstack-formulas/php-formula/issues/47#issuecomment-174576699)

**Comment by julianfirminger-united** [comment]
A different cause might be you have a entry in the top.sls (foo) and your minions usually have grains.item foo = bar but in this instance foo is null.  
I.e. if top.sls evaluates a grain, it cant handle it if the grain is present but null
