### ISSUE TITLE
not working with salt-ssh

### ISSUE THREAD

**Issue by grimaz** [saltstack-formulas/php-formula#196]
Sample sls
```
php:
  warning_messages:
    v1.0.0:
      mute_critical: true
      mute_upcoming: true
  use_external_repo: true
  external_repo_name: 'ondrej/php'
  version: "7.3"

  modules:
    - cli
    - curl
    - mysql

  use_apache_formula: true

```
produces the error
```
[DEBUG   ] Results of YAML rendering:
OrderedDict([(u'php_ppa_php', OrderedDict([(u'pkgrepo.managed', [OrderedDict([(u'ppa', u'ondrej/php')]), OrderedDict([(u'__env__', [OrderedDict([(u'LC_ALL', u'C.UTF-8')])])]), OrderedDict([(u'onlyif', [u'test ! -e /etc/apt/sources.list.d/ondrej-ubuntu-php-xenial.list', u'test ! -e /etc/apt/sources.list.d/ondrej-php-xenial.list'])]), OrderedDict([(u'require_in', [OrderedDict([(u'pkg', u'php_install_php')])])])]), (u'pkg.latest', [OrderedDict([(u'name', u'php')]), OrderedDict([(u'pkgs', [u'php7.3'])]), OrderedDict([(u'refresh', True)]), OrderedDict([(u'onchanges', [OrderedDict([(u'pkgrepo', u'php_ppa_php')])])])])])), (u'php_install_php', OrderedDict([(u'pkg.installed', [OrderedDict([(u'name', u'php')]), OrderedDict([(u'pkgs', [u'php7.3'])])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/master/files/base/php/init.sls' using 'yaml' renderer: 0.00143599510193
[ERROR   ] TypeError encountered executing state.apply: unhashable type: 'list'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 1180, in run_wfunc
    result = self.wfuncs[self.fun](*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/wrapper/state.py", line 522, in apply_
    return highstate(**kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/wrapper/state.py", line 694, in highstate
    opts.get('extra_filerefs', '')
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/state.py", line 138, in lowstate_file_refs
    if saltenv not in refs:
TypeError: unhashable type: 'list'
```

**Comment by BillyBombardieri** [comment]
I have this also
